# Generated by Django 5.1.5 on 2025-01-18 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDataMainModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('main_url', models.CharField(max_length=255)),
                ('short_url', models.CharField(max_length=150, unique=True)),
                ('expiry_time', models.DateTimeField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='ShortUrlApp.urldatamainmodel')),
            ],
        ),
    ]
