# Generated by Django 5.1.5 on 2025-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortUrlApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslogs',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='urldatamainmodel',
            name='creation_time',
            field=models.DateTimeField(),
        ),
    ]
